### ISSUE TITLE
Fails with joins

### ISSUE THREAD

**Issue by dragosionescuu** [cannblw/knex-paginator#4]
This fails when there are joins in the initial query as it's removing them. How can we make it work with a join statement?

**Comment by m-salamon** [comment]
I found an interesting issue, happens only when `isLengthAware = true`, I tried joining on a table called 'items' and when i tried doing a `where clause` i got an `unknown column error`

**Comment by cannblw** [comment]
I merged @xausky's pull request. It should be working now.
