### ISSUE TITLE
Total field diffier amount when i groupby

### ISSUE THREAD

**Issue by aepel** [cannblw/knex-paginator#7]
Hi, thanks for this excellent plugin. I'm having difficulties when I have a query with the groupby statement.
If the query returns a list without groupby it works very well.
If I add the group by statement, the total returns the number 2, which has nothing to do with the number of results that the query without groupby returns to me.
Could you help me?

**Comment by aepel** [comment]
My fault sorry for the inconvenience

**Comment by cannblw** [comment]
Glad you got it sorted!
